# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
    syren7_owncloud.filesystem.class: Syren7\OwncloudApiBundle\Service\OwncloudFilesystem
    syren7_owncloud.user.class: Syren7\OwncloudApiBundle\Service\OwncloudUser

services:
    syren7_owncloud.filesystem:
        class: "%syren7_owncloud.filesystem.class%"
        arguments: [@service_container]

    syren7_owncloud.user:
        class: "%syren7_owncloud.user.class%"
        arguments: [@service_container]